# A influência da aleatoriedade na validação do modelo

In [2]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/e99a526b2e7ccc6c3b70f53db43a87d2/raw/1605fc74aa778066bf2e6695e24d53cf65f2f447/machine-learning-carros-simulacao.csv"
dados = pd.read_csv(uri).drop(columns=["Unnamed: 0"], axis=1)
dados.head()

preco  vendido  idade_do_modelo   km_por_ano
0   30941.02        1               18  35085.22134
1   40557.96        1               20  12622.05362
2   89627.50        0               12  11440.79806
3   95276.14        0                3  43167.32682
4  117384.68        1                4  12770.11290

* Vamos separar os dados em x e y. Sendo x o que queremos analisar e y a nossa classificação.

In [3]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   preco            10000 non-null  float64
 1   vendido          10000 non-null  int64  
 2   idade_do_modelo  10000 non-null  int64  
 3   km_por_ano       10000 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 312.6 KB


## Separando a base de dados

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

x = dados[["preco", "idade_do_modelo","km_por_ano"]]
y = dados["vendido"]

SEED = 158020
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25,
                                                         stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

Treinaremos com 7500 elementos e testaremos com 2500 elementos


## Criando um baseline

In [5]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier(strategy='stratified')
dummy_stratified.fit(treino_x, treino_y)
acuracia = dummy_stratified.score(teste_x, teste_y) * 100

print("A acurácia do dummy stratified foi de %.2f%%" % acuracia)

A acurácia do dummy stratified foi de 50.96%


In [6]:
from sklearn.tree import DecisionTreeClassifier

SEED = 56
np.random.seed(SEED)
modelo = DecisionTreeClassifier(max_depth=2)
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print ("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 71.92%


# Usando e avaliando com o cross validate

In [7]:
from sklearn.model_selection import cross_validate

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3)
results

{'fit_time': array([0.00721717, 0.00499988, 0.00600004]),
 'score_time': array([0.00178409, 0.00200033, 0.00099945]),
 'test_score': array([0.75704859, 0.7629763 , 0.75337534])}

In [8]:
from sklearn.model_selection import cross_validate

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
results

{'fit_time': array([0.00652075, 0.00602508, 0.00501704]),
 'score_time': array([0.00226188, 0.00198412, 0.00198221]),
 'test_score': array([0.75704859, 0.7629763 , 0.75337534])}

In [9]:
from sklearn.model_selection import cross_validate

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
results['test_score']

array([0.75704859, 0.7629763 , 0.75337534])

In [10]:
from sklearn.model_selection import cross_validate

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
media = results ['test_score'].mean()
media

0.7578000751484867

In [11]:
from sklearn.model_selection import cross_validate

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
media = results ['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy %.2f %.2f" % (media - 2 * desvio_padrao, media + 2 * desvio_padrao))

Accuracy 0.75 0.77


In [12]:
from sklearn.model_selection import cross_validate

SEED = 158020
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
media = results ['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy [%.2f, %.2f]" % ((media - 2 *desvio_padrao) * 100, (media + 2 * desvio_padrao) * 100))

Accuracy [74.99, 76.57]


In [13]:
from sklearn.model_selection import cross_validate

SEED = 158020
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
media = results ['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 3 = [%.2f, %.2f]" % ((media - 2 *desvio_padrao) * 100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 3 = [74.99, 76.57]


In [14]:
from sklearn.model_selection import cross_validate

SEED = 42
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
media = results ['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 3 = [%.2f, %.2f]" % ((media - 2 *desvio_padrao) * 100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 3 = [74.99, 76.57]


In [15]:
from sklearn.model_selection import cross_validate

SEED = 42
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 5, return_train_score=False)
media = results ['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 5 = [%.2f, %.2f]" % ((media - 2 *desvio_padrao) * 100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 5 = [75.21, 76.35]


In [16]:
from sklearn.model_selection import cross_validate

SEED = 42
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 10, return_train_score=False)
media = results ['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 10 = [%.2f, %.2f]" % ((media - 2 *desvio_padrao) * 100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 10 = [74.24, 77.32]


# Kfold com aleatorização

In [17]:
from sklearn.model_selection import KFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = KFold(n_splits = k)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)

media = results['test_score'].mean()
desvio_padrao = results['test_score'].std()
epslon_plus = (media + 2*desvio_padrao)*100
epslon_minus = (media - 2*desvio_padrao)*100

print(f"Accuracy com cross validation {k} = [{epslon_minus:.2f}, {epslon_plus:.2f}] em %.")

Accuracy com cross validation 10 = [74.37, 77.19] em %.


In [18]:
def imprimir_results(results, k):
    
    media = results['test_score'].mean()
    desvio_padrao = results['test_score'].std()
    epslon_plus = (media + 2*desvio_padrao)*100
    epslon_minus = (media - 2*desvio_padrao)*100
    print(f"Accuracy da média: {media:.2%}")
    print(f"Accuracy com cross validation {k} = [{epslon_minus:.2f}, {epslon_plus:.2f}] em %.")


In [19]:
from sklearn.model_selection import KFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = KFold(n_splits = k)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 75.78%
Accuracy com cross validation 10 = [74.37, 77.19] em %.


In [20]:
from sklearn.model_selection import KFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = KFold(n_splits = k, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 75.76%
Accuracy com cross validation 10 = [73.26, 78.26] em %.


# Estratificação com validação cruzada

## Simular uma situação horrível de azar
* Pode ser "azar" como pode ser uma porporção de samples desbalanceada.

In [29]:
dados.head(10)

preco  vendido  idade_do_modelo   km_por_ano
0   30941.02        1               18  35085.22134
1   40557.96        1               20  12622.05362
2   89627.50        0               12  11440.79806
3   95276.14        0                3  43167.32682
4  117384.68        1                4  12770.11290
5   55405.26        1               11  23594.53374
6   93415.61        1               16  16077.30660
7   65265.09        0               10  18666.73466
8   43917.53        1               19  12607.56956
9  107860.41        1               15  24000.08742

In [22]:
dados.sort_values('vendido', ascending=True)

preco  vendido  idade_do_modelo   km_por_ano
4999  74023.29        0               12  24812.80412
5322  84843.49        0               13  23095.63834
5319  83100.27        0               19  36240.72746
5316  87932.13        0               16  32249.56426
5315  77937.01        0               15  28414.50704
...        ...      ...              ...          ...
5491  71910.43        1                9  25778.40812
1873  30456.53        1                6  15468.97608
1874  69342.41        1               11  16909.33538
5499  70520.39        1               16  19622.68262
0     30941.02        1               18  35085.22134

[10000 rows x 4 columns]

In [26]:
dados_azar = dados.sort_values('vendido', ascending=True)
x_azar = dados_azar[["preco", "idade_do_modelo","km_por_ano"]]
y_azar = dados_azar["vendido"]

## Testando com e sem Shuffle

In [31]:
from sklearn.model_selection import KFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = KFold(n_splits = k)
modelo = DecisionTreeClassifier(max_depth=2)

results = cross_validate(modelo, 
                         x_azar, 
                         y_azar, 
                         cv = cv, 
                         return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 57.84%
Accuracy com cross validation 10 = [34.29, 81.39] em %.


In [32]:
from sklearn.model_selection import KFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = KFold(n_splits = k, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)

results = cross_validate(modelo, 
                         x_azar, 
                         y_azar, 
                         cv = cv, 
                         return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 75.78%
Accuracy com cross validation 10 = [72.30, 79.26] em %.


## Testando com o Stratified

In [34]:
from sklearn.model_selection import StratifiedKFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = StratifiedKFold(n_splits = k)
modelo = DecisionTreeClassifier(max_depth=2)

results = cross_validate(modelo, 
                         x_azar, 
                         y_azar, 
                         cv = cv, 
                         return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 75.78%
Accuracy com cross validation 10 = [73.83, 77.73] em %.


In [33]:
from sklearn.model_selection import StratifiedKFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = StratifiedKFold(n_splits = k, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)

results = cross_validate(modelo, 
                         x_azar, 
                         y_azar, 
                         cv = cv, 
                         return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 75.78%
Accuracy com cross validation 10 = [73.55, 78.01] em %.


## Referências:

* Link para pesquisa: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.model_selection

# Gerando dados aleatórios

In [35]:
np.random.seed(SEED)
np.random.randint(-2, 3, size=10000)

array([-2,  2,  0, ...,  0,  2,  2])

In [36]:
np.random.seed(SEED)
dados["modelo_aleatorio"] = dados.idade_do_modelo + np.random.randint(-2, 3, size=10000)
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo_aleatorio
0   30941.02        1               18  35085.22134                16
1   40557.96        1               20  12622.05362                22
2   89627.50        0               12  11440.79806                12
3   95276.14        0                3  43167.32682                 4
4  117384.68        1                4  12770.11290                 3

In [37]:
dados.modelo_aleatorio.unique()

array([16, 22, 12,  4,  3, 11, 18, 17, 13,  0, 15, 10,  9, 14,  1,  5, 19,
       21,  8,  7, 20,  6,  2, -1], dtype=int64)

In [38]:
dados.modelo_aleatorio.min()

-1

In [39]:
abs(dados.modelo_aleatorio.min())

1

In [43]:
dados.modelo_aleatorio = dados.modelo_aleatorio + abs(dados.modelo_aleatorio.min()) + 1
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo_aleatorio
0   30941.02        1               18  35085.22134                18
1   40557.96        1               20  12622.05362                24
2   89627.50        0               12  11440.79806                14
3   95276.14        0                3  43167.32682                 6
4  117384.68        1                4  12770.11290                 5

In [44]:
dados.modelo_aleatorio.unique()

array([18, 24, 14,  6,  5, 13, 20, 19, 15,  2, 17, 12, 11, 16,  3,  7, 21,
       23, 10,  9, 22,  8,  4,  1], dtype=int64)

In [45]:
dados.modelo_aleatorio.min()

1

* Fazendo tudo de uma vez só:

In [46]:
np.random.seed(SEED)
dados["modelo_aleatorio"] = dados.idade_do_modelo + np.random.randint(-2, 3, size=10000)
dados.modelo_aleatorio = dados.modelo_aleatorio + abs(dados.modelo_aleatorio.min()) + 1
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo_aleatorio
0   30941.02        1               18  35085.22134                18
1   40557.96        1               20  12622.05362                24
2   89627.50        0               12  11440.79806                14
3   95276.14        0                3  43167.32682                 6
4  117384.68        1                4  12770.11290                 5

In [47]:
dados.modelo_aleatorio.unique()

array([18, 24, 14,  6,  5, 13, 20, 19, 15,  2, 17, 12, 11, 16,  3,  7, 21,
       23, 10,  9, 22,  8,  4,  1], dtype=int64)

In [48]:
np.random.seed(SEED)
dados["modelo"] = dados.idade_do_modelo + np.random.randint(-2, 3, size=10000)
dados.modelo = dados.modelo + abs(dados.modelo.min()) + 1
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo_aleatorio  modelo
0   30941.02        1               18  35085.22134                18      18
1   40557.96        1               20  12622.05362                24      24
2   89627.50        0               12  11440.79806                14      14
3   95276.14        0                3  43167.32682                 6       6
4  117384.68        1                4  12770.11290                 5       5

In [50]:
dados.modelo.value_counts()

20    901
19    798
18    771
21    723
17    709
16    668
14    621
22    575
15    573
13    557
12    511
11    401
10    371
23    370
9     336
8     278
7     206
24    199
6     181
5     108
4      76
3      44
2      17
1       6
Name: modelo, dtype: int64

In [51]:
dados = dados.drop(columns=["modelo_aleatorio"], axis=1)
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo
0   30941.02        1               18  35085.22134      18
1   40557.96        1               20  12622.05362      24
2   89627.50        0               12  11440.79806      14
3   95276.14        0                3  43167.32682       6
4  117384.68        1                4  12770.11290       5

# Validação cruzada usando grupos (GroupKFold)

## Referências:

* Link para pesquisa: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GroupKFold.html

In [52]:
from sklearn.model_selection import GroupKFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = GroupKFold(n_splits = k)
modelo = DecisionTreeClassifier(max_depth=2)

results = cross_validate(modelo, 
                         x_azar, 
                         y_azar, 
                         cv = cv,
                         groups=dados.modelo,
                         return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 75.78%
Accuracy com cross validation 10 = [73.67, 77.90] em %.


# A importância do pipeline no crossvalidate

In [56]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

SEED = 301
np.random.seed(SEED)

scaler = StandardScaler()
scaler.fit(treino_x)
treino_x_escalado = scaler.transform(treino_x)
teste_x_escalado = scaler.transform(teste_x)

modelo = SVC()
modelo.fit(treino_x_escalado, treino_y)
previsoes = modelo.predict(teste_x_escalado)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi de %.2f %%" % acuracia)

A acurácia foi de 74.40 %


In [58]:
from sklearn.model_selection import GroupKFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = GroupKFold(n_splits = k)
modelo = SVC()

results = cross_validate(modelo, 
                         x_azar, 
                         y_azar, 
                         cv = cv,
                         groups=dados.modelo,
                         return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 77.27%
Accuracy com cross validation 10 = [74.35, 80.20] em %.


In [59]:
scaler = StandardScaler()
scaler.fit(x_azar)
x_azar_escalado = scaler.transform(x_azar)

In [60]:
x_azar_escalado

array([[ 0.3636103 , -0.39591706,  0.24651152],
       [ 0.79214444, -0.18257669,  0.03346607],
       [ 0.72310419,  1.09746554,  1.66435195],
       ...,
       [ 0.17822399, -0.60925743, -0.73405662],
       [ 0.2248779 ,  0.45744443, -0.39741686],
       [-1.34266351,  0.88412517,  1.52099053]])

In [62]:
from sklearn.model_selection import GroupKFold

SEED = 301
np.random.seed(SEED)

k = 10
cv = GroupKFold(n_splits = k)
modelo = SVC()
results = cross_validate(modelo, x_azar_escalado, y_azar, cv = cv, groups = dados.modelo,return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 76.70%
Accuracy com cross validation 10 = [74.30, 79.10] em %.


In [66]:
from sklearn.pipeline import Pipeline

scaler =StandardScaler()
modelo = SVC()

pipeline = Pipeline([('transformacao', scaler), ('estimador', modelo)])
pipeline

Pipeline(steps=[('transformacao', StandardScaler()), ('estimador', SVC())])

In [69]:
from sklearn.pipeline import Pipeline

SEED = 301
np.random.seed(SEED)

scaler =StandardScaler()
modelo = SVC()

pipeline = Pipeline([('transformacao', scaler), ('estimador', modelo)])

k = 10
cv = GroupKFold(n_splits = k)
result = cross_validate(pipeline, x_azar, y_azar, cv = cv, groups = dados.modelo, return_train_score=False)
imprimir_results(results, k)

Accuracy da média: 76.70%
Accuracy com cross validation 10 = [74.30, 79.10] em %.
